package com.quickmindgames.sudoku.utils

object AnalyticsConstants {

    //region screen_view events
    const val HOME = "Home"
    const val HOME_SCREEN = "HomeScreen"
    const val STATISTICS = "Statistics"
    const val STATISTICS_SCREEN = "StatisticsScreen"
    const val SETTINGS = "Settings"
    const val SETTINGS_SCREEN = "SettingsScreen"
    const val REWARDS = "Rewards"
    const val REWARDS_SCREEN = "RewardsScreen"
    const val STREAK = "Streak"
    const val STREAK_SCREEN = "StreakScreen"
    const val SUDOKU_GAME = "Sudoku Game"
    const val SUDOKU_SCREEN = "SudokuScreen"
    const val LESSON = "Lesson"
    const val LESSON_SCREEN = "LessonScreen"
    //endregion

    //region Feature events
    const val NEW_GAME = "new_game"
    const val STREAK_GAME = "streak_game"
    const val DIFFICULTY = "difficulty"
    const val DIFFICULTY_BY_HINTS = "difficulty_by_hints"
    const val SAVED_GAME = "saved_game"
    const val RESUME_GAME = "resume_game"
    const val STREAK_COUNT = "streak_count"
    const val STREAK_COMPLETED = "streak_completed"
    const val STREAK_STARTED = "streak_started"
    const val STREAK_COUNT_SHARE = "streak_count_share"
    const val GAME_RESULT = "game_result"
    const val RESULT = "result"
    const val WIN = "win"
    const val LOSS = "loss"
    const val TIME = "time"
    const val MISTAKES = "mistakes"
    const val SCORE = "score"
    const val GAME_ACTION = "game_action"
    const val ACTION = "action"
    const val HINT = "hint"
    const val NOTES = "notes"
    const val NOTES_ON = "notes_on"
    const val NOTES_OFF = "notes_off"
    const val STATE = "state"
    const val ON = "on"
    const val OFF = "off"
    const val UNDO = "undo"
    const val ERASE = "erase"
    const val THEME = "theme"
    const val THEME_TOGGLED = "theme_toggled"
    const val SETTINGS_OPTION_CHANGED = "settings_option_changed"
    const val SETTING = "setting"
    const val NOTIFICATION_RECEIVED = "notification_received"
    const val NOTIFICATION_CLICKED = "notification_clicked"
    const val STREAK_SHARE = "streak_share"
    const val STREAK_TAB = "streak_tab"
    const val IS_STREAK = "is_streak"
    const val HINT_COUNT = "hints_used"
    const val STATISTICS_EVENT = "statistics"
    const val LESSON_STARTED = "lesson_started"
    const val LEARNING_MODE = "learning_mode"
    const val LESSON_COMPLETED = "lesson_completed"
    const val SETTINGS_STATE = "settings_state"
    const val HIDE_USED_NUMBERS = "hide_used_numbers"
    const val HIGHLIGHT_SAME_NUMBERS = "highlight_same_numbers"
    const val HIGHLIGHT_REGION = "highlight_region"
    const val FREE_PLAY = "free_play"
    const val SOUND_VIBRATIONS = "sound_vibration"
    const val YES = "Yes"
    const val NO = "No"
    //endregion

}
